flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from flask_login import current_user
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


#Data required prevents field from beinge empty, Length restricts length
#Create a class. In bracket include what the class inherits from

class PostForm(FlaskForm):
    title= StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flaskblog/main/routes.py
from flask import Blueprint
from flask import render_template, request
from flaskblog.models import Post
main = Blueprint('main', __name__)

#use main.route instead of app.route
@main.route("/")
@main.route("/home")
def home():
    #display all posts on home screen
    # posts = Post.query.all() is used to show all pages on home page. Paginate shows a particular number
    page = request.args.get('page', 1, type=int) #not needed for query.all
    posts = Post.query.order_by(Post.date.desc()).paginate(page=page, per_page=3) #3 posts per page. .order_by is only needed if you want to order
    return render_template('home.html', posts=posts)

@main.route("/about")
def about():
   return render_template('about.html')

flaskblog/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flaskblog import db 
from flaskblog.posts.forms import PostForm
from flaskblog.models import Post
from flask_login import current_user, login_required 

posts = Blueprint('posts', __name__)
#change all @app.route to users. route...users is defined with blueprint above

@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        #Add new post to db. You can use id or current user for author
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post', legend='Update Post', form=form)

# create a route to open a post by defining a function for each post
@posts.route("/post/<int:post_id>") #just viewing so no need for get or post request
def post(post_id):
    #you can use get method because its an id
    post = Post.query.get_or_404(post_id) #if post with that id doesnt exist, give a 404 error
    return render_template('post.html', title=post.title, post=post)

#route to update a post
@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id) #if post with that id doesnt exist, give a 404 error
    #only owners of post should be able to update it. use post.author to access user model
    if post.author != current_user:
        abort(403) #403 is http response for forbidden route
    form = PostForm()
    if form.validate_on_submit():
        post.title=form.title.data
        post.content=form.content.data
        db.session.commit()  #no need to add, post is already in the db
        flash('Your post has been Updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method =='GET':
    #UPDATE post on post page and home page
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post', legend='Update Post', form=form)

#Delete route: No get request 
@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id) #if post with that id doesnt exist, give a 404 error
    #only owners of post should be able to update it. To link post and user, use author i.e post.author
    if post.author != current_user:
        abort(403) #403 is http response for forbidden route
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been Deleted!', 'success')
    return redirect(url_for('main.home'))

flaskblog/users/routes.py
#create users blueprint
from flask import Blueprint
from flask import render_template, url_for, flash, redirect, request
from flaskblog import db, bcrypt
from flaskblog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from flaskblog.models import User, Post
from flask_login import login_user, current_user, logout_user, login_required 
from flaskblog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)
#change all @app.route to users. route...users is defined with blueprint above

@users.route("/register", methods=['GET', 'POST'])
# include methods to accept both post and get requests so that registration forms can submit
def register():
    #condition prevents register page from opening after user has logged in already
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        # if form submits, hash the passwords in db. Then add registered users to database
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You can now log in', 'success')
        return redirect(url_for('users.login'))
        # After successful submission, redirect to home page. success after form.username is a bootsrap attribute
    return render_template('register.html', title='Register', form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():
    #condition prevents login page from opening after user has logged in already. If current user is logged in rediret to home page
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        #Check if any email in database is equal to input email
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            #login_user function takes in a remeber arguement as well
            login_user(user, remember=form.remember.data)
            #If a user tries to access account page directly by putting /account in browser withou logging in, they will
            #be redirected to login page after which they should be redirected to the page they want instead of home
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form) 

#create logout route
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/account", methods=['GET', 'POST'])
#login is required for account route to work
@login_required
def account():
    form = UpdateAccountForm()
    #change username and email on account page 
    if form.validate_on_submit():
        #save picture on account with file name created above
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file #image_file is used in model whilr picture is used in forms
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated', 'success')
        return redirect(url_for('users.account'))
    #display current username and email on account page
    elif request.method=='GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form) 

#posts for one user
@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    # get all posts by this user
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date.desc()).paginate(page=page, per_page=3) 
    return render_template('user_posts.html', posts=posts, user=user)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    #User has to be logged out to access this page. If current user is logged in rediret to home page
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit:
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

#route to reset password
@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    #User has to be logged out to access this page. If current user is logged in rediret to home page
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        # if form submits, hash the passwords in db. Then add registered users to database
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You can now log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

flaskblog/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

flaskblog/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ image_file }}">
            <div class="media body" style = "display:flex;flex-direction:column">
                <h2 class="account-heading"> {{ current_user.username }}</h2>
                <p class="text-secondary"> {{ current_user.email }} </p>
            </div>
        </div>
        <!-- add special encoding type (enctype) to form so that it can pass image data properly -->
            <form method="POST" action="", enctype="multipart/form-data"> 
            <!-- action means when you post the form its posts to the same route you are currently on -->
            <!-- when you are accessing varriables in template, wrap text in 2 curly bracket. Hiidden tag also protects form -->
                {{form.hidden_tag()}}
                <fieldset class="form-group">
                <legend class ="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{form.username.label(class="form-control-label")}}
                    <!-- to display errors for each field. Errors depends on what is specified in -->
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}    
                </div>
                <div class="form-group">
                    {{form.email.label(class="form-control-label")}}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{form.email(class="form-control form-control-lg")}}
                    {% endif %}   
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                        <!-- invalid feedback div of class of text danger makes error messages red -->
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
                </fieldset>
                <div class="form-group">
                    {{form.submit(class="btn btn-outline-info")}}
                </div>
            </form> 
    </div>
{% endblock content %}

flaskblog/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action=""> 
    <!-- action means when you post the form its posts to the same route you are currently on -->
    <!-- when you are accessing varriables in template, wrap text in 2 curly bracket. Hiidden tag also protects form -->
        {{form.hidden_tag()}}
        <fieldset class="form-group">
        <!-- this form is used for both new and update post so legend is different. Specify legend in route.py -->
        <legend class ="border-bottom mb-4">{{legend}}</legend>
        <div class="form-group">
            <!-- create flash error. Error will occur due to requirement in form.py -->
            {{form.title.label(class="form-control-label")}}
            {% if form.title.errors %}
                {{ form.title(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.title.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{form.title(class="form-control form-control-lg")}}
            {% endif %}   
        </div>
        <div class="form-group">
            {{form.content.label(class="form-control-label")}}
            {% if form.content.errors %}
                {{ form.content(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.content.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{form.content(class="form-control form-control-lg")}}
            {% endif %}    
        </div>
        </fieldset>
        <div class="form-group">
            {{form.submit(class="btn btn-outline-info")}}
        </div>
    </form>
</div>
{% endblock content %}

flaskblog/templates/home.html
{% extends "layout.html" %}
<!-- how posts should be created how posts should be created. for post in posts is used if post.query.all is used in /home route  -->
<!-- posts.items is used because of pagination -->
{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
 <!-- display image with post.articl-img is designed with main.css, include it for img to have proper size and padding  -->
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{url_for('users.user_posts', username=post.author.username)}}">{{ post.author.username }}</a> <!-- display only username -->
              <!-- display only date no time. specify format for date -->
              <small class="text-muted">{{ post.date.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{url_for('posts.post', post_id=post.id)}}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    <!-- add a button that links to next page and other pages -->
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
      <!-- style the number of the current page differently -->
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{url_for('main.home', page=page_num)}}">{{page_num}}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{url_for('main.home', page=page_num)}}">{{page_num}}</a>
         {% endif %} 
      {% else %}
      ...
      {% endif %} 
    {% endfor %}
{% endblock content %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    {% if title %}
        <title>Flask Blog - {{ title }}</title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Flask Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <!-- href="/home" or "{{ url_for('main.home') }}""  -->
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
               {% if current_user.is_authenticated %}
               <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
               <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
               <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
               {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          <!-- To display flash messages -->
          {% with messages = get_flashed_messages(with_categories=true) %} 
          <!-- to print out messages if any, use if statement -->
            {% if messages %} 
            <!-- loop over messages with for statement -->
              {% for category, message in messages %} 
                <div class="alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {%endif %}          
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

flaskblog/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action=""> 
        <!-- action means when you post the form its posts to the same route you are currently on -->
        <!-- when you are accessing varriables in template, wrap text in 2 curly bracket. Hiidden tag also protects form -->
            {{form.hidden_tag()}}
            <fieldset class="form-group">
            <legend class ="border-bottom mb-4">Log In</legend>
            <div class="form-group">
                {{form.email.label(class="form-control-label")}}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.email(class="form-control form-control-lg")}}
                {% endif %}   
            </div>
            <div class="form-group">
                {{form.password.label(class="form-control-label")}}
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.password(class="form-control form-control-lg")}}
                {% endif %}    
            </div>
            <div>
                <div class ="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </div>
            </fieldset>
            <div class="form-group">
                {{form.submit(class="btn btn-outline-info")}}
                <small class="text-muted ml-2">
                    <a href="{{url_for('users.reset_request')}}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            <!-- text muted makes text a bit blurred -->
            Need an account? <a class="ml-2" href="{{url_for('users.register')}}">Sign Up Now</a>
            <!-- note that login after url for is name of def not route -->
        </small>
    </div>
{% endblock content %}
<!-- form-control-label, text-muted etc are all attributes of bootstrap that make your blog nicer -->

flaskblog/templates/post.html
{% extends "layout.html" %}
{% block content %}
<!-- how posts should be created -->
    <article class="media content-section">
<!-- display image with post.articl-img is designed with main.css, include it for img to have proper size and padding  -->
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{{url_for('users.user_posts', username=post.author.username)}}">{{ post.author.username }}</a> <!-- display only username -->
            <!-- display only date no time. specify format for date -->
            <small class="text-muted">{{ post.date.strftime('%Y-%m-%d') }}</small>
            <!-- add update and delete button but should only be visciblle to owners of post -->
            {% if post.author == current_user %}
                <div>
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{url_for('posts.update_post', post_id=post.id)}}">Update</a>
        <!-- use delete modal to allow users be asked if they want to delete before deleting. Search for delete modal online -->
                    <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                </div>
            {% endif %}
        </div>
        <h2 class="article-title">{{ post.title }}</h2>
        <p class="article-content">{{ post.content }}</p>
        </div>
    </article>
    <!-- Modal -->
<div class="modal fade" id="deleteModal" tab index="1" role="dialog" aria-label="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">Are you sure you want to delete this post?</div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

flaskblog/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action=""> 
        <!-- action means when you post the form its posts to the same route you are currently on -->
        <!-- when you are accessing varriables in template, wrap text in 2 curly bracket. Hiidden tag also protects form -->
            {{form.hidden_tag()}}
            <fieldset class="form-group">
            <legend class ="border-bottom mb-4">Reset Password</legend>
            <div class="form-group">
                {{form.email.label(class="form-control-label")}}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.email(class="form-control form-control-lg")}}
                {% endif %}   
            </div>
            </fieldset>
            <div class="form-group">
                {{form.submit(class="btn btn-outline-info")}}
            </div>
        </form>
    </div>
{% endblock content %}
<!-- form-control-label, text-muted etc are all attributes of bootstrap that make your blog nicer -->

flaskblog/templates/user_posts.html
{% extends "layout.html" %}
<!-- how posts should be created how posts should be created. for post in posts is used if post.query.all is used in /home route  -->
<!-- posts.items is used because of pagination -->
{% block content %}
<h1 class="mb-3">Posts by {{user.username}} ( {{posts.total}} )</h1>
    {% for post in posts.items %}
        <article class="media content-section">
 <!-- display image with post.articl-img is designed with main.css, include it for img to have proper size and padding  -->
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2">{{ post.author.username }}</a> <!-- display only username -->
              <!-- display only date no time. specify format for date -->
              <small class="text-muted">{{ post.date.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{url_for('posts.post', post_id=post.id)}}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    <!-- add a button that links to next page and other pages -->
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
      <!-- style the number of the current page differently -->
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{url_for('users.user_posts', username=user.username, page=page_num)}}">{{page_num}}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{url_for('users.user_posts', username=user.username, page=page_num)}}">{{page_num}}</a>
         {% endif %} 
      {% else %}
      ...
      {% endif %} 
    {% endfor %}
{% endblock content %}